### PR TITLE
Add weight to Voter

### PR DESCRIPTION
**Pull request by SeanWorkman**

### CODE REVIEW

**Comment by SeanWorkman** [comment]
@dturrina is that what you were looking for?

**Comment by dturrina** [comment]
Good job!
Do you think it would be better to set 1.0 as default weight, so that weighted operations result is identical to standard operations and not 0?

**Comment by SeanWorkman** [comment]
Yea it probably would make more sense to have everyone start at 1.0 sorry about that

**Comment by dturrina** [comment]
It's ok. Everyone has her way to think, plus the default float is ALWAYS 0.0 - this can be considered an exceptional case, as we could need to present a result to users.

**Comment by SeanWorkman** [comment]
Ok should I go in and fix those things and submit another pull request

**Comment by dturrina** [comment]
It would be great. I know it's a very little point, but I really do not have time for it.
If you don't have time, too, please let me know. Thank you.

**Comment by SeanWorkman** [comment]
so just change the 
```java
private double weight=0.0;
```
to
```java
private double weight=1.0;
```

**Comment by dturrina** [comment]
Yes. Could you please do it? Thank you.

**Comment by SeanWorkman** [comment]
That good

**Pull request merged**
